version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./dolphindb:/docker-entrypoint-initdb.d
    restart: always
  
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/dev.archive:/Databases/dev.archive
      - ./mongo/production:/Databases/production
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

  eureka-server:
    build: ./registry/
    image: registry-image
    ports:
      - 8888:8888

  gateway-service:
    build: ./gateway/
    image: gateway-image
    depends_on:
      - eureka-server
    ports:
      - 7778:7778
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"


  ms-auth-service:
    build: ./ms_auth_admin/
    image: ms-auth-image
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/users
      spring.datasource.password: password
    restart: on-failure


  ms-demande-service:
    build: ./ms-demandeV3/
    image: ms-demande-image
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/demandes
      spring.datasource.password: password
    restart: on-failure


  ms-gestion-document-service:
    build: ./ms-gestion-document-v2/
    image: ms-gestion-document-image
    depends_on:
      - eureka-server
      - gateway-service
      - mongo
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.data.mongodb.host: "mongo"
      spring.data.mongodb.port: 27017
      spring.data.mongodb.database: gestion-document
    restart: on-failure

  ms-notification-service:
    build: ./ms-notification/
    image: ms-notification-image
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/notifications
      spring.datasource.password: password
    restart: on-failure

  ms-citizen-social-service:
    build: ./ms-participation-citoyen/
    image: ms-citizen-social-image
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/citizen_social
      spring.datasource.password: password
    restart: on-failure


