version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./dolphindb:/docker-entrypoint-initdb.d
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - 'node.role == manager'
  
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/dev.archive:/Databases/dev.archive
      - ./mongo/production:/Databases/production
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - 'node.role == manager'

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure

  eureka-server:
    image: registry-image
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - 'node.role == manager'

  gateway-service:
    image: gateway-image
    ports:
      - "7778:7778"
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - 'node.role == manager'


  ms-auth-service:
    image: madd47emz/wathaequi:ms-auth
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/users
      spring.datasource.password: password
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  ms-demande-service:
    image: madd47emz/wathaequi:ms-demande-management
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/demandes
      spring.datasource.password: password
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: on-failure


  ms-gestion-document-service:
    image: madd47emz/wathaequi:ms-document-management
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.data.mongodb.host: "mongo"
      spring.data.mongodb.port: 27017
      spring.data.mongodb.database: gestion-document
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: on-failure

  ms-notification-service:
    image: madd47emz/wathaequi:ms-citizen-notification
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/notifications
      spring.datasource.password: password
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: on-failure

  ms-citizen-social-service:
    image: madd47emz/wathaequi:ms-citizen-social
    environment:
      profile: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"
      spring.datasource.url: jdbc:mysql://mysql:3306/citizen_social
      spring.datasource.password: password
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: on-failure


