apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway-service
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-server:8888/eureka
            - name: profile
              value: default
          image: gateway-image
          name: gateway-service
          ports:
            - containerPort: 7778
          resources: {}
      restartPolicy: Always
status: {}
