apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  ports:
    - name: "7778"
      port: 7778
      targetPort: 7778
  selector:
    io.kompose.service: gateway-service
status:
  loadBalancer: {}
